var __defProp = Object.defineProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};

// src/app.ts
import express7 from "express";
import cors from "cors";

// src/routes/index.ts
import { Router as Router2 } from "express";

// src/modules/auth/auth.route.ts
import express from "express";

// src/modules/auth/auth.service.ts
import bcrypt from "bcrypt";

// src/lib/prisma.ts
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";

// generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.4.1",
  "engineVersion": "55ae170b1ced7fc6ed07a15f110549408c501bb3",
  "activeProvider": "postgresql",
  "inlineSchema": 'generator client {\n  provider = "prisma-client"\n  output   = "../generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nenum UserRole {\n  ADMIN\n  TUTOR\n  STUDENT\n}\n\nenum UserStatus {\n  ACTIVE\n  BANNED\n}\n\nenum BookingStatus {\n  CONFIRMED\n  CANCELED\n  COMPLETED\n}\n\nmodel User {\n  id       String     @id @default(uuid())\n  email    String     @unique\n  password String\n  name     String\n  role     UserRole\n  status   UserStatus @default(ACTIVE)\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  tutorProfile TutorProfile?\n  bookings     Booking[]\n  reviews      Review[]\n\n  @@index([role])\n  @@index([status])\n  @@map("users")\n}\n\nmodel TutorProfile {\n  id         String  @id @default(uuid())\n  bio        String?\n  experience Int\n  hourlyRate Float\n\n  isFeatured    Boolean @default(false)\n  totalReviews  Int     @default(0)\n  averageRating Float   @default(0)\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  userId String @unique\n  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  availability Availability[]\n  categories   Category[]     @relation("TutorCategories")\n  bookings     Booking[]\n  reviews      Review[]\n\n  @@map("tutorProfiles")\n}\n\nmodel Category {\n  id           String @id @default(uuid())\n  categoryName String @unique\n\n  createdAt DateTime @default(now())\n\n  tutors TutorProfile[] @relation("TutorCategories")\n\n  @@map("categories")\n}\n\nmodel Availability {\n  id         String   @id @default(uuid())\n  startTime  DateTime\n  endTime    DateTime\n  totalPrice Float\n  createdAt  DateTime @default(now())\n  updatedAt  DateTime @updatedAt\n  isBooked   Boolean  @default(false)\n\n  tutorId      String\n  tutorProfile TutorProfile @relation(fields: [tutorId], references: [id], onDelete: Cascade)\n  booking      Booking?\n\n  @@index([tutorId])\n  @@map("availabilities")\n}\n\nmodel Booking {\n  id     String        @id @default(uuid())\n  notes  String?\n  status BookingStatus @default(CONFIRMED)\n\n  tutorId        String\n  studentId      String\n  availabilityId String @unique\n\n  createdAt DateTime @default(now())\n\n  tutor        TutorProfile @relation(fields: [tutorId], references: [id], onDelete: Cascade)\n  student      User         @relation(fields: [studentId], references: [id], onDelete: Cascade)\n  availability Availability @relation(fields: [availabilityId], references: [id], onDelete: Cascade)\n  review       Review?\n\n  @@index([studentId])\n  @@index([tutorId])\n  @@map("bookings")\n}\n\nmodel Review {\n  id      String  @id @default(uuid())\n  rating  Int\n  comment String?\n\n  createdAt DateTime @default(now())\n\n  studentId String\n  tutorId   String\n  bookingId String @unique\n\n  student User         @relation(fields: [studentId], references: [id], onDelete: Cascade)\n  tutor   TutorProfile @relation(fields: [tutorId], references: [id], onDelete: Cascade)\n  booking Booking      @relation(fields: [bookingId], references: [id], onDelete: Cascade)\n\n  @@index([tutorId])\n  @@index([studentId])\n  @@map("reviews")\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"role","kind":"enum","type":"UserRole"},{"name":"status","kind":"enum","type":"UserStatus"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"tutorProfile","kind":"object","type":"TutorProfile","relationName":"TutorProfileToUser"},{"name":"bookings","kind":"object","type":"Booking","relationName":"BookingToUser"},{"name":"reviews","kind":"object","type":"Review","relationName":"ReviewToUser"}],"dbName":"users"},"TutorProfile":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"bio","kind":"scalar","type":"String"},{"name":"experience","kind":"scalar","type":"Int"},{"name":"hourlyRate","kind":"scalar","type":"Float"},{"name":"isFeatured","kind":"scalar","type":"Boolean"},{"name":"totalReviews","kind":"scalar","type":"Int"},{"name":"averageRating","kind":"scalar","type":"Float"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"TutorProfileToUser"},{"name":"availability","kind":"object","type":"Availability","relationName":"AvailabilityToTutorProfile"},{"name":"categories","kind":"object","type":"Category","relationName":"TutorCategories"},{"name":"bookings","kind":"object","type":"Booking","relationName":"BookingToTutorProfile"},{"name":"reviews","kind":"object","type":"Review","relationName":"ReviewToTutorProfile"}],"dbName":"tutorProfiles"},"Category":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"categoryName","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"tutors","kind":"object","type":"TutorProfile","relationName":"TutorCategories"}],"dbName":"categories"},"Availability":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"startTime","kind":"scalar","type":"DateTime"},{"name":"endTime","kind":"scalar","type":"DateTime"},{"name":"totalPrice","kind":"scalar","type":"Float"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"isBooked","kind":"scalar","type":"Boolean"},{"name":"tutorId","kind":"scalar","type":"String"},{"name":"tutorProfile","kind":"object","type":"TutorProfile","relationName":"AvailabilityToTutorProfile"},{"name":"booking","kind":"object","type":"Booking","relationName":"AvailabilityToBooking"}],"dbName":"availabilities"},"Booking":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"notes","kind":"scalar","type":"String"},{"name":"status","kind":"enum","type":"BookingStatus"},{"name":"tutorId","kind":"scalar","type":"String"},{"name":"studentId","kind":"scalar","type":"String"},{"name":"availabilityId","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"tutor","kind":"object","type":"TutorProfile","relationName":"BookingToTutorProfile"},{"name":"student","kind":"object","type":"User","relationName":"BookingToUser"},{"name":"availability","kind":"object","type":"Availability","relationName":"AvailabilityToBooking"},{"name":"review","kind":"object","type":"Review","relationName":"BookingToReview"}],"dbName":"bookings"},"Review":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"rating","kind":"scalar","type":"Int"},{"name":"comment","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"studentId","kind":"scalar","type":"String"},{"name":"tutorId","kind":"scalar","type":"String"},{"name":"bookingId","kind":"scalar","type":"String"},{"name":"student","kind":"object","type":"User","relationName":"ReviewToUser"},{"name":"tutor","kind":"object","type":"TutorProfile","relationName":"ReviewToTutorProfile"},{"name":"booking","kind":"object","type":"Booking","relationName":"BookingToReview"}],"dbName":"reviews"}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","user","orderBy","cursor","tutorProfile","tutor","student","availability","booking","review","tutors","_count","categories","bookings","reviews","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","data","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","create","update","User.upsertOne","User.deleteOne","User.deleteMany","having","_min","_max","User.groupBy","User.aggregate","TutorProfile.findUnique","TutorProfile.findUniqueOrThrow","TutorProfile.findFirst","TutorProfile.findFirstOrThrow","TutorProfile.findMany","TutorProfile.createOne","TutorProfile.createMany","TutorProfile.createManyAndReturn","TutorProfile.updateOne","TutorProfile.updateMany","TutorProfile.updateManyAndReturn","TutorProfile.upsertOne","TutorProfile.deleteOne","TutorProfile.deleteMany","_avg","_sum","TutorProfile.groupBy","TutorProfile.aggregate","Category.findUnique","Category.findUniqueOrThrow","Category.findFirst","Category.findFirstOrThrow","Category.findMany","Category.createOne","Category.createMany","Category.createManyAndReturn","Category.updateOne","Category.updateMany","Category.updateManyAndReturn","Category.upsertOne","Category.deleteOne","Category.deleteMany","Category.groupBy","Category.aggregate","Availability.findUnique","Availability.findUniqueOrThrow","Availability.findFirst","Availability.findFirstOrThrow","Availability.findMany","Availability.createOne","Availability.createMany","Availability.createManyAndReturn","Availability.updateOne","Availability.updateMany","Availability.updateManyAndReturn","Availability.upsertOne","Availability.deleteOne","Availability.deleteMany","Availability.groupBy","Availability.aggregate","Booking.findUnique","Booking.findUniqueOrThrow","Booking.findFirst","Booking.findFirstOrThrow","Booking.findMany","Booking.createOne","Booking.createMany","Booking.createManyAndReturn","Booking.updateOne","Booking.updateMany","Booking.updateManyAndReturn","Booking.upsertOne","Booking.deleteOne","Booking.deleteMany","Booking.groupBy","Booking.aggregate","Review.findUnique","Review.findUniqueOrThrow","Review.findFirst","Review.findFirstOrThrow","Review.findMany","Review.createOne","Review.createMany","Review.createManyAndReturn","Review.updateOne","Review.updateMany","Review.updateManyAndReturn","Review.upsertOne","Review.deleteOne","Review.deleteMany","Review.groupBy","Review.aggregate","AND","OR","NOT","id","rating","comment","createdAt","studentId","tutorId","bookingId","equals","in","notIn","lt","lte","gt","gte","not","contains","startsWith","endsWith","notes","BookingStatus","status","availabilityId","startTime","endTime","totalPrice","updatedAt","isBooked","categoryName","bio","experience","hourlyRate","isFeatured","totalReviews","averageRating","userId","email","password","name","UserRole","role","UserStatus","every","some","none","is","isNot","connectOrCreate","upsert","disconnect","delete","connect","set","updateMany","deleteMany","createMany","increment","decrement","multiply","divide"]'),
  graph: "vAM6YA4EAADPAQAgDQAA0AEAIA4AANEBACB3AADKAQAweAAAJAAQeQAAygEAMHoBAAAAAX1AAM4BACGOAQAAzQGjASKTAUAAzgEAIZ0BAQAAAAGeAQEAywEAIZ8BAQDLAQAhoQEAAMwBoQEiAQAAAAEAIBIBAADVAQAgBwAA3wEAIAwAAOABACANAADQAQAgDgAA0QEAIHcAANwBADB4AAADABB5AADcAQAwegEAywEAIX1AAM4BACGTAUAAzgEAIZYBAQDUAQAhlwECANMBACGYAQgA3QEAIZkBIADeAQAhmgECANMBACGbAQgA3QEAIZwBAQDLAQAhAQAAAAMAIA0EAADWAQAgCAAA5AEAIHcAAOMBADB4AAAFABB5AADjAQAwegEAywEAIX1AAM4BACF_AQDLAQAhkAFAAM4BACGRAUAAzgEAIZIBCADdAQAhkwFAAM4BACGUASAA3gEAIQIEAACGAwAgCAAAigMAIA0EAADWAQAgCAAA5AEAIHcAAOMBADB4AAAFABB5AADjAQAwegEAAAABfUAAzgEAIX8BAMsBACGQAUAAzgEAIZEBQADOAQAhkgEIAN0BACGTAUAAzgEAIZQBIADeAQAhAwAAAAUAIAIAAAYAMAMAAAcAIA4FAADWAQAgBgAA1QEAIAcAANoBACAJAADbAQAgdwAA2AEAMHgAAAkAEHkAANgBADB6AQDLAQAhfUAAzgEAIX4BAMsBACF_AQDLAQAhjAEBANQBACGOAQAA2QGOASKPAQEAywEAIQEAAAAJACANBQAA1gEAIAYAANUBACAIAADXAQAgdwAA0gEAMHgAAAsAEHkAANIBADB6AQDLAQAhewIA0wEAIXwBANQBACF9QADOAQAhfgEAywEAIX8BAMsBACGAAQEAywEAIQEAAAALACAHCgAA4gEAIHcAAOEBADB4AAANABB5AADhAQAwegEAywEAIX1AAM4BACGVAQEAywEAIQEKAACPAwAgBwoAAOIBACB3AADhAQAweAAADQAQeQAA4QEAMHoBAAAAAX1AAM4BACGVAQEAAAABAwAAAA0AIAIAAA4AMAMAAA8AIAYBAACJAwAgBwAAjQMAIAwAAI4DACANAACHAwAgDgAAiAMAIJYBAADlAQAgEgEAANUBACAHAADfAQAgDAAA4AEAIA0AANABACAOAADRAQAgdwAA3AEAMHgAAAMAEHkAANwBADB6AQAAAAF9QADOAQAhkwFAAM4BACGWAQEA1AEAIZcBAgDTAQAhmAEIAN0BACGZASAA3gEAIZoBAgDTAQAhmwEIAN0BACGcAQEAAAABAwAAAAMAIAIAABEAMAMAABIAIAEAAAADACAFBQAAhgMAIAYAAIkDACAHAACLAwAgCQAAjAMAIIwBAADlAQAgDgUAANYBACAGAADVAQAgBwAA2gEAIAkAANsBACB3AADYAQAweAAACQAQeQAA2AEAMHoBAAAAAX1AAM4BACF-AQDLAQAhfwEAywEAIYwBAQDUAQAhjgEAANkBjgEijwEBAAAAAQMAAAAJACACAAAVADADAAAWACAEBQAAhgMAIAYAAIkDACAIAACKAwAgfAAA5QEAIA0FAADWAQAgBgAA1QEAIAgAANcBACB3AADSAQAweAAACwAQeQAA0gEAMHoBAAAAAXsCANMBACF8AQDUAQAhfUAAzgEAIX4BAMsBACF_AQDLAQAhgAEBAAAAAQMAAAALACACAAAYADADAAAZACABAAAABQAgAQAAAA0AIAEAAAAJACABAAAACwAgAwAAAAkAIAIAABUAMAMAABYAIAMAAAALACACAAAYADADAAAZACABAAAACQAgAQAAAAsAIAEAAAABACAOBAAAzwEAIA0AANABACAOAADRAQAgdwAAygEAMHgAACQAEHkAAMoBADB6AQDLAQAhfUAAzgEAIY4BAADNAaMBIpMBQADOAQAhnQEBAMsBACGeAQEAywEAIZ8BAQDLAQAhoQEAAMwBoQEiAwQAAIYDACANAACHAwAgDgAAiAMAIAMAAAAkACACAAAlADADAAABACADAAAAJAAgAgAAJQAwAwAAAQAgAwAAACQAIAIAACUAMAMAAAEAIAsEAACDAwAgDQAAhAMAIA4AAIUDACB6AQAAAAF9QAAAAAGOAQAAAKMBApMBQAAAAAGdAQEAAAABngEBAAAAAZ8BAQAAAAGhAQAAAKEBAgEUAAApACAIegEAAAABfUAAAAABjgEAAACjAQKTAUAAAAABnQEBAAAAAZ4BAQAAAAGfAQEAAAABoQEAAAChAQIBFAAAKwAwARQAACsAMAsEAADpAgAgDQAA6gIAIA4AAOsCACB6AQDrAQAhfUAA7gEAIY4BAADoAqMBIpMBQADuAQAhnQEBAOsBACGeAQEA6wEAIZ8BAQDrAQAhoQEAAOcCoQEiAgAAAAEAIBQAAC4AIAh6AQDrAQAhfUAA7gEAIY4BAADoAqMBIpMBQADuAQAhnQEBAOsBACGeAQEA6wEAIZ8BAQDrAQAhoQEAAOcCoQEiAgAAACQAIBQAADAAIAIAAAAkACAUAAAwACADAAAAAQAgGwAAKQAgHAAALgAgAQAAAAEAIAEAAAAkACADCwAA5AIAICEAAOYCACAiAADlAgAgC3cAAMMBADB4AAA3ABB5AADDAQAwegEAqQEAIX1AAKwBACGOAQAAxQGjASKTAUAArAEAIZ0BAQCpAQAhngEBAKkBACGfAQEAqQEAIaEBAADEAaEBIgMAAAAkACACAAA2ADAgAAA3ACADAAAAJAAgAgAAJQAwAwAAAQAgAQAAABIAIAEAAAASACADAAAAAwAgAgAAEQAwAwAAEgAgAwAAAAMAIAIAABEAMAMAABIAIAMAAAADACACAAARADADAAASACAPAQAAzQIAIAcAAM4CACAMAADjAgAgDQAAzwIAIA4AANACACB6AQAAAAF9QAAAAAGTAUAAAAABlgEBAAAAAZcBAgAAAAGYAQgAAAABmQEgAAAAAZoBAgAAAAGbAQgAAAABnAEBAAAAAQEUAAA_ACAKegEAAAABfUAAAAABkwFAAAAAAZYBAQAAAAGXAQIAAAABmAEIAAAAAZkBIAAAAAGaAQIAAAABmwEIAAAAAZwBAQAAAAEBFAAAQQAwARQAAEEAMA8BAACkAgAgBwAApQIAIAwAANcCACANAACmAgAgDgAApwIAIHoBAOsBACF9QADuAQAhkwFAAO4BACGWAQEA7QEAIZcBAgDsAQAhmAEIAIsCACGZASAAjAIAIZoBAgDsAQAhmwEIAIsCACGcAQEA6wEAIQIAAAASACAUAABEACAKegEA6wEAIX1AAO4BACGTAUAA7gEAIZYBAQDtAQAhlwECAOwBACGYAQgAiwIAIZkBIACMAgAhmgECAOwBACGbAQgAiwIAIZwBAQDrAQAhAgAAAAMAIBQAAEYAIAIAAAADACAUAABGACADAAAAEgAgGwAAPwAgHAAARAAgAQAAABIAIAEAAAADACAGCwAA0gIAICEAANUCACAiAADUAgAgMwAA0wIAIDQAANYCACCWAQAA5QEAIA13AADCAQAweAAATQAQeQAAwgEAMHoBAKkBACF9QACsAQAhkwFAAKwBACGWAQEAqwEAIZcBAgCqAQAhmAEIALwBACGZASAAvQEAIZoBAgCqAQAhmwEIALwBACGcAQEAqQEAIQMAAAADACACAABMADAgAABNACADAAAAAwAgAgAAEQAwAwAAEgAgAQAAAA8AIAEAAAAPACADAAAADQAgAgAADgAwAwAADwAgAwAAAA0AIAIAAA4AMAMAAA8AIAMAAAANACACAAAOADADAAAPACAECgAA0QIAIHoBAAAAAX1AAAAAAZUBAQAAAAEBFAAAVQAgA3oBAAAAAX1AAAAAAZUBAQAAAAEBFAAAVwAwARQAAFcAMAQKAACZAgAgegEA6wEAIX1AAO4BACGVAQEA6wEAIQIAAAAPACAUAABaACADegEA6wEAIX1AAO4BACGVAQEA6wEAIQIAAAANACAUAABcACACAAAADQAgFAAAXAAgAwAAAA8AIBsAAFUAIBwAAFoAIAEAAAAPACABAAAADQAgAwsAAJYCACAhAACYAgAgIgAAlwIAIAZ3AADBAQAweAAAYwAQeQAAwQEAMHoBAKkBACF9QACsAQAhlQEBAKkBACEDAAAADQAgAgAAYgAwIAAAYwAgAwAAAA0AIAIAAA4AMAMAAA8AIAEAAAAHACABAAAABwAgAwAAAAUAIAIAAAYAMAMAAAcAIAMAAAAFACACAAAGADADAAAHACADAAAABQAgAgAABgAwAwAABwAgCgQAAJQCACAIAACVAgAgegEAAAABfUAAAAABfwEAAAABkAFAAAAAAZEBQAAAAAGSAQgAAAABkwFAAAAAAZQBIAAAAAEBFAAAawAgCHoBAAAAAX1AAAAAAX8BAAAAAZABQAAAAAGRAUAAAAABkgEIAAAAAZMBQAAAAAGUASAAAAABARQAAG0AMAEUAABtADAKBAAAjQIAIAgAAI4CACB6AQDrAQAhfUAA7gEAIX8BAOsBACGQAUAA7gEAIZEBQADuAQAhkgEIAIsCACGTAUAA7gEAIZQBIACMAgAhAgAAAAcAIBQAAHAAIAh6AQDrAQAhfUAA7gEAIX8BAOsBACGQAUAA7gEAIZEBQADuAQAhkgEIAIsCACGTAUAA7gEAIZQBIACMAgAhAgAAAAUAIBQAAHIAIAIAAAAFACAUAAByACADAAAABwAgGwAAawAgHAAAcAAgAQAAAAcAIAEAAAAFACAFCwAAhgIAICEAAIkCACAiAACIAgAgMwAAhwIAIDQAAIoCACALdwAAuwEAMHgAAHkAEHkAALsBADB6AQCpAQAhfUAArAEAIX8BAKkBACGQAUAArAEAIZEBQACsAQAhkgEIALwBACGTAUAArAEAIZQBIAC9AQAhAwAAAAUAIAIAAHgAMCAAAHkAIAMAAAAFACACAAAGADADAAAHACABAAAAFgAgAQAAABYAIAMAAAAJACACAAAVADADAAAWACADAAAACQAgAgAAFQAwAwAAFgAgAwAAAAkAIAIAABUAMAMAABYAIAsFAACCAgAgBgAAgwIAIAcAAIQCACAJAACFAgAgegEAAAABfUAAAAABfgEAAAABfwEAAAABjAEBAAAAAY4BAAAAjgECjwEBAAAAAQEUAACBAQAgB3oBAAAAAX1AAAAAAX4BAAAAAX8BAAAAAYwBAQAAAAGOAQAAAI4BAo8BAQAAAAEBFAAAgwEAMAEUAACDAQAwCwUAAPkBACAGAAD6AQAgBwAA-wEAIAkAAPwBACB6AQDrAQAhfUAA7gEAIX4BAOsBACF_AQDrAQAhjAEBAO0BACGOAQAA-AGOASKPAQEA6wEAIQIAAAAWACAUAACGAQAgB3oBAOsBACF9QADuAQAhfgEA6wEAIX8BAOsBACGMAQEA7QEAIY4BAAD4AY4BIo8BAQDrAQAhAgAAAAkAIBQAAIgBACACAAAACQAgFAAAiAEAIAMAAAAWACAbAACBAQAgHAAAhgEAIAEAAAAWACABAAAACQAgBAsAAPUBACAhAAD3AQAgIgAA9gEAIIwBAADlAQAgCncAALcBADB4AACPAQAQeQAAtwEAMHoBAKkBACF9QACsAQAhfgEAqQEAIX8BAKkBACGMAQEAqwEAIY4BAAC4AY4BIo8BAQCpAQAhAwAAAAkAIAIAAI4BADAgAACPAQAgAwAAAAkAIAIAABUAMAMAABYAIAEAAAAZACABAAAAGQAgAwAAAAsAIAIAABgAMAMAABkAIAMAAAALACACAAAYADADAAAZACADAAAACwAgAgAAGAAwAwAAGQAgCgUAAPMBACAGAADyAQAgCAAA9AEAIHoBAAAAAXsCAAAAAXwBAAAAAX1AAAAAAX4BAAAAAX8BAAAAAYABAQAAAAEBFAAAlwEAIAd6AQAAAAF7AgAAAAF8AQAAAAF9QAAAAAF-AQAAAAF_AQAAAAGAAQEAAAABARQAAJkBADABFAAAmQEAMAoFAADwAQAgBgAA7wEAIAgAAPEBACB6AQDrAQAhewIA7AEAIXwBAO0BACF9QADuAQAhfgEA6wEAIX8BAOsBACGAAQEA6wEAIQIAAAAZACAUAACcAQAgB3oBAOsBACF7AgDsAQAhfAEA7QEAIX1AAO4BACF-AQDrAQAhfwEA6wEAIYABAQDrAQAhAgAAAAsAIBQAAJ4BACACAAAACwAgFAAAngEAIAMAAAAZACAbAACXAQAgHAAAnAEAIAEAAAAZACABAAAACwAgBgsAAOYBACAhAADpAQAgIgAA6AEAIDMAAOcBACA0AADqAQAgfAAA5QEAIAp3AACoAQAweAAApQEAEHkAAKgBADB6AQCpAQAhewIAqgEAIXwBAKsBACF9QACsAQAhfgEAqQEAIX8BAKkBACGAAQEAqQEAIQMAAAALACACAACkAQAwIAAApQEAIAMAAAALACACAAAYADADAAAZACAKdwAAqAEAMHgAAKUBABB5AACoAQAwegEAqQEAIXsCAKoBACF8AQCrAQAhfUAArAEAIX4BAKkBACF_AQCpAQAhgAEBAKkBACEOCwAArgEAICEAALYBACAiAAC2AQAggQEBAAAAAYIBAQAAAASDAQEAAAAEhAEBAAAAAYUBAQAAAAGGAQEAAAABhwEBAAAAAYgBAQC1AQAhiQEBAAAAAYoBAQAAAAGLAQEAAAABDQsAAK4BACAhAACuAQAgIgAArgEAIDMAALQBACA0AACuAQAggQECAAAAAYIBAgAAAASDAQIAAAAEhAECAAAAAYUBAgAAAAGGAQIAAAABhwECAAAAAYgBAgCzAQAhDgsAALEBACAhAACyAQAgIgAAsgEAIIEBAQAAAAGCAQEAAAAFgwEBAAAABYQBAQAAAAGFAQEAAAABhgEBAAAAAYcBAQAAAAGIAQEAsAEAIYkBAQAAAAGKAQEAAAABiwEBAAAAAQsLAACuAQAgIQAArwEAICIAAK8BACCBAUAAAAABggFAAAAABIMBQAAAAASEAUAAAAABhQFAAAAAAYYBQAAAAAGHAUAAAAABiAFAAK0BACELCwAArgEAICEAAK8BACAiAACvAQAggQFAAAAAAYIBQAAAAASDAUAAAAAEhAFAAAAAAYUBQAAAAAGGAUAAAAABhwFAAAAAAYgBQACtAQAhCIEBAgAAAAGCAQIAAAAEgwECAAAABIQBAgAAAAGFAQIAAAABhgECAAAAAYcBAgAAAAGIAQIArgEAIQiBAUAAAAABggFAAAAABIMBQAAAAASEAUAAAAABhQFAAAAAAYYBQAAAAAGHAUAAAAABiAFAAK8BACEOCwAAsQEAICEAALIBACAiAACyAQAggQEBAAAAAYIBAQAAAAWDAQEAAAAFhAEBAAAAAYUBAQAAAAGGAQEAAAABhwEBAAAAAYgBAQCwAQAhiQEBAAAAAYoBAQAAAAGLAQEAAAABCIEBAgAAAAGCAQIAAAAFgwECAAAABYQBAgAAAAGFAQIAAAABhgECAAAAAYcBAgAAAAGIAQIAsQEAIQuBAQEAAAABggEBAAAABYMBAQAAAAWEAQEAAAABhQEBAAAAAYYBAQAAAAGHAQEAAAABiAEBALIBACGJAQEAAAABigEBAAAAAYsBAQAAAAENCwAArgEAICEAAK4BACAiAACuAQAgMwAAtAEAIDQAAK4BACCBAQIAAAABggECAAAABIMBAgAAAASEAQIAAAABhQECAAAAAYYBAgAAAAGHAQIAAAABiAECALMBACEIgQEIAAAAAYIBCAAAAASDAQgAAAAEhAEIAAAAAYUBCAAAAAGGAQgAAAABhwEIAAAAAYgBCAC0AQAhDgsAAK4BACAhAAC2AQAgIgAAtgEAIIEBAQAAAAGCAQEAAAAEgwEBAAAABIQBAQAAAAGFAQEAAAABhgEBAAAAAYcBAQAAAAGIAQEAtQEAIYkBAQAAAAGKAQEAAAABiwEBAAAAAQuBAQEAAAABggEBAAAABIMBAQAAAASEAQEAAAABhQEBAAAAAYYBAQAAAAGHAQEAAAABiAEBALYBACGJAQEAAAABigEBAAAAAYsBAQAAAAEKdwAAtwEAMHgAAI8BABB5AAC3AQAwegEAqQEAIX1AAKwBACF-AQCpAQAhfwEAqQEAIYwBAQCrAQAhjgEAALgBjgEijwEBAKkBACEHCwAArgEAICEAALoBACAiAAC6AQAggQEAAACOAQKCAQAAAI4BCIMBAAAAjgEIiAEAALkBjgEiBwsAAK4BACAhAAC6AQAgIgAAugEAIIEBAAAAjgECggEAAACOAQiDAQAAAI4BCIgBAAC5AY4BIgSBAQAAAI4BAoIBAAAAjgEIgwEAAACOAQiIAQAAugGOASILdwAAuwEAMHgAAHkAEHkAALsBADB6AQCpAQAhfUAArAEAIX8BAKkBACGQAUAArAEAIZEBQACsAQAhkgEIALwBACGTAUAArAEAIZQBIAC9AQAhDQsAAK4BACAhAAC0AQAgIgAAtAEAIDMAALQBACA0AAC0AQAggQEIAAAAAYIBCAAAAASDAQgAAAAEhAEIAAAAAYUBCAAAAAGGAQgAAAABhwEIAAAAAYgBCADAAQAhBQsAAK4BACAhAAC_AQAgIgAAvwEAIIEBIAAAAAGIASAAvgEAIQULAACuAQAgIQAAvwEAICIAAL8BACCBASAAAAABiAEgAL4BACECgQEgAAAAAYgBIAC_AQAhDQsAAK4BACAhAAC0AQAgIgAAtAEAIDMAALQBACA0AAC0AQAggQEIAAAAAYIBCAAAAASDAQgAAAAEhAEIAAAAAYUBCAAAAAGGAQgAAAABhwEIAAAAAYgBCADAAQAhBncAAMEBADB4AABjABB5AADBAQAwegEAqQEAIX1AAKwBACGVAQEAqQEAIQ13AADCAQAweAAATQAQeQAAwgEAMHoBAKkBACF9QACsAQAhkwFAAKwBACGWAQEAqwEAIZcBAgCqAQAhmAEIALwBACGZASAAvQEAIZoBAgCqAQAhmwEIALwBACGcAQEAqQEAIQt3AADDAQAweAAANwAQeQAAwwEAMHoBAKkBACF9QACsAQAhjgEAAMUBowEikwFAAKwBACGdAQEAqQEAIZ4BAQCpAQAhnwEBAKkBACGhAQAAxAGhASIHCwAArgEAICEAAMkBACAiAADJAQAggQEAAAChAQKCAQAAAKEBCIMBAAAAoQEIiAEAAMgBoQEiBwsAAK4BACAhAADHAQAgIgAAxwEAIIEBAAAAowECggEAAACjAQiDAQAAAKMBCIgBAADGAaMBIgcLAACuAQAgIQAAxwEAICIAAMcBACCBAQAAAKMBAoIBAAAAowEIgwEAAACjAQiIAQAAxgGjASIEgQEAAACjAQKCAQAAAKMBCIMBAAAAowEIiAEAAMcBowEiBwsAAK4BACAhAADJAQAgIgAAyQEAIIEBAAAAoQECggEAAAChAQiDAQAAAKEBCIgBAADIAaEBIgSBAQAAAKEBAoIBAAAAoQEIgwEAAAChAQiIAQAAyQGhASIOBAAAzwEAIA0AANABACAOAADRAQAgdwAAygEAMHgAACQAEHkAAMoBADB6AQDLAQAhfUAAzgEAIY4BAADNAaMBIpMBQADOAQAhnQEBAMsBACGeAQEAywEAIZ8BAQDLAQAhoQEAAMwBoQEiC4EBAQAAAAGCAQEAAAAEgwEBAAAABIQBAQAAAAGFAQEAAAABhgEBAAAAAYcBAQAAAAGIAQEAtgEAIYkBAQAAAAGKAQEAAAABiwEBAAAAAQSBAQAAAKEBAoIBAAAAoQEIgwEAAAChAQiIAQAAyQGhASIEgQEAAACjAQKCAQAAAKMBCIMBAAAAowEIiAEAAMcBowEiCIEBQAAAAAGCAUAAAAAEgwFAAAAABIQBQAAAAAGFAUAAAAABhgFAAAAAAYcBQAAAAAGIAUAArwEAIRQBAADVAQAgBwAA3wEAIAwAAOABACANAADQAQAgDgAA0QEAIHcAANwBADB4AAADABB5AADcAQAwegEAywEAIX1AAM4BACGTAUAAzgEAIZYBAQDUAQAhlwECANMBACGYAQgA3QEAIZkBIADeAQAhmgECANMBACGbAQgA3QEAIZwBAQDLAQAhpgEAAAMAIKcBAAADACADowEAAAkAIKQBAAAJACClAQAACQAgA6MBAAALACCkAQAACwAgpQEAAAsAIA0FAADWAQAgBgAA1QEAIAgAANcBACB3AADSAQAweAAACwAQeQAA0gEAMHoBAMsBACF7AgDTAQAhfAEA1AEAIX1AAM4BACF-AQDLAQAhfwEAywEAIYABAQDLAQAhCIEBAgAAAAGCAQIAAAAEgwECAAAABIQBAgAAAAGFAQIAAAABhgECAAAAAYcBAgAAAAGIAQIArgEAIQuBAQEAAAABggEBAAAABYMBAQAAAAWEAQEAAAABhQEBAAAAAYYBAQAAAAGHAQEAAAABiAEBALIBACGJAQEAAAABigEBAAAAAYsBAQAAAAEQBAAAzwEAIA0AANABACAOAADRAQAgdwAAygEAMHgAACQAEHkAAMoBADB6AQDLAQAhfUAAzgEAIY4BAADNAaMBIpMBQADOAQAhnQEBAMsBACGeAQEAywEAIZ8BAQDLAQAhoQEAAMwBoQEipgEAACQAIKcBAAAkACAUAQAA1QEAIAcAAN8BACAMAADgAQAgDQAA0AEAIA4AANEBACB3AADcAQAweAAAAwAQeQAA3AEAMHoBAMsBACF9QADOAQAhkwFAAM4BACGWAQEA1AEAIZcBAgDTAQAhmAEIAN0BACGZASAA3gEAIZoBAgDTAQAhmwEIAN0BACGcAQEAywEAIaYBAAADACCnAQAAAwAgEAUAANYBACAGAADVAQAgBwAA2gEAIAkAANsBACB3AADYAQAweAAACQAQeQAA2AEAMHoBAMsBACF9QADOAQAhfgEAywEAIX8BAMsBACGMAQEA1AEAIY4BAADZAY4BIo8BAQDLAQAhpgEAAAkAIKcBAAAJACAOBQAA1gEAIAYAANUBACAHAADaAQAgCQAA2wEAIHcAANgBADB4AAAJABB5AADYAQAwegEAywEAIX1AAM4BACF-AQDLAQAhfwEAywEAIYwBAQDUAQAhjgEAANkBjgEijwEBAMsBACEEgQEAAACOAQKCAQAAAI4BCIMBAAAAjgEIiAEAALoBjgEiDwQAANYBACAIAADkAQAgdwAA4wEAMHgAAAUAEHkAAOMBADB6AQDLAQAhfUAAzgEAIX8BAMsBACGQAUAAzgEAIZEBQADOAQAhkgEIAN0BACGTAUAAzgEAIZQBIADeAQAhpgEAAAUAIKcBAAAFACAPBQAA1gEAIAYAANUBACAIAADXAQAgdwAA0gEAMHgAAAsAEHkAANIBADB6AQDLAQAhewIA0wEAIXwBANQBACF9QADOAQAhfgEAywEAIX8BAMsBACGAAQEAywEAIaYBAAALACCnAQAACwAgEgEAANUBACAHAADfAQAgDAAA4AEAIA0AANABACAOAADRAQAgdwAA3AEAMHgAAAMAEHkAANwBADB6AQDLAQAhfUAAzgEAIZMBQADOAQAhlgEBANQBACGXAQIA0wEAIZgBCADdAQAhmQEgAN4BACGaAQIA0wEAIZsBCADdAQAhnAEBAMsBACEIgQEIAAAAAYIBCAAAAASDAQgAAAAEhAEIAAAAAYUBCAAAAAGGAQgAAAABhwEIAAAAAYgBCAC0AQAhAoEBIAAAAAGIASAAvwEAIQOjAQAABQAgpAEAAAUAIKUBAAAFACADowEAAA0AIKQBAAANACClAQAADQAgBwoAAOIBACB3AADhAQAweAAADQAQeQAA4QEAMHoBAMsBACF9QADOAQAhlQEBAMsBACEDowEAAAMAIKQBAAADACClAQAAAwAgDQQAANYBACAIAADkAQAgdwAA4wEAMHgAAAUAEHkAAOMBADB6AQDLAQAhfUAAzgEAIX8BAMsBACGQAUAAzgEAIZEBQADOAQAhkgEIAN0BACGTAUAAzgEAIZQBIADeAQAhEAUAANYBACAGAADVAQAgBwAA2gEAIAkAANsBACB3AADYAQAweAAACQAQeQAA2AEAMHoBAMsBACF9QADOAQAhfgEAywEAIX8BAMsBACGMAQEA1AEAIY4BAADZAY4BIo8BAQDLAQAhpgEAAAkAIKcBAAAJACAAAAAAAAABrQEBAAAAAQWtAQIAAAABsQECAAAAAbIBAgAAAAGzAQIAAAABtAECAAAAAQGtAQEAAAABAa0BQAAAAAEFGwAAsgMAIBwAALsDACCoAQAAswMAIKkBAAC6AwAgrAEAAAEAIAUbAACwAwAgHAAAuAMAIKgBAACxAwAgqQEAALcDACCsAQAAEgAgBRsAAK4DACAcAAC1AwAgqAEAAK8DACCpAQAAtAMAIKwBAAAWACADGwAAsgMAIKgBAACzAwAgrAEAAAEAIAMbAACwAwAgqAEAALEDACCsAQAAEgAgAxsAAK4DACCoAQAArwMAIKwBAAAWACAAAAABrQEAAACOAQIFGwAAowMAIBwAAKwDACCoAQAApAMAIKkBAACrAwAgrAEAABIAIAUbAAChAwAgHAAAqQMAIKgBAACiAwAgqQEAAKgDACCsAQAAAQAgBRsAAJ8DACAcAACmAwAgqAEAAKADACCpAQAApQMAIKwBAAAHACAHGwAA_QEAIBwAAIACACCoAQAA_gEAIKkBAAD_AQAgqgEAAAsAIKsBAAALACCsAQAAGQAgCAUAAPMBACAGAADyAQAgegEAAAABewIAAAABfAEAAAABfUAAAAABfgEAAAABfwEAAAABAgAAABkAIBsAAP0BACADAAAACwAgGwAA_QEAIBwAAIECACAKAAAACwAgBQAA8AEAIAYAAO8BACAUAACBAgAgegEA6wEAIXsCAOwBACF8AQDtAQAhfUAA7gEAIX4BAOsBACF_AQDrAQAhCAUAAPABACAGAADvAQAgegEA6wEAIXsCAOwBACF8AQDtAQAhfUAA7gEAIX4BAOsBACF_AQDrAQAhAxsAAKMDACCoAQAApAMAIKwBAAASACADGwAAoQMAIKgBAACiAwAgrAEAAAEAIAMbAACfAwAgqAEAAKADACCsAQAABwAgAxsAAP0BACCoAQAA_gEAIKwBAAAZACAAAAAAAAWtAQgAAAABsQEIAAAAAbIBCAAAAAGzAQgAAAABtAEIAAAAAQGtASAAAAABBRsAAJoDACAcAACdAwAgqAEAAJsDACCpAQAAnAMAIKwBAAASACAHGwAAjwIAIBwAAJICACCoAQAAkAIAIKkBAACRAgAgqgEAAAkAIKsBAAAJACCsAQAAFgAgCQUAAIICACAGAACDAgAgCQAAhQIAIHoBAAAAAX1AAAAAAX4BAAAAAX8BAAAAAYwBAQAAAAGOAQAAAI4BAgIAAAAWACAbAACPAgAgAwAAAAkAIBsAAI8CACAcAACTAgAgCwAAAAkAIAUAAPkBACAGAAD6AQAgCQAA_AEAIBQAAJMCACB6AQDrAQAhfUAA7gEAIX4BAOsBACF_AQDrAQAhjAEBAO0BACGOAQAA-AGOASIJBQAA-QEAIAYAAPoBACAJAAD8AQAgegEA6wEAIX1AAO4BACF-AQDrAQAhfwEA6wEAIYwBAQDtAQAhjgEAAPgBjgEiAxsAAJoDACCoAQAAmwMAIKwBAAASACADGwAAjwIAIKgBAACQAgAgrAEAABYAIAAAAAobAACaAgAwHAAAngIAMKgBAACbAgAwqQEAAJwCADCqAQAAnQIAMKsBAACdAgAwrAEAAJ0CADCtAQAAnQIAMK4BAACfAgAwrwEAAKACADAOAQAAzQIAIAcAAM4CACANAADPAgAgDgAA0AIAIHoBAAAAAX1AAAAAAZMBQAAAAAGWAQEAAAABlwECAAAAAZgBCAAAAAGZASAAAAABmgECAAAAAZsBCAAAAAGcAQEAAAABAgAAABIAIBsAAMwCACADAAAAEgAgGwAAzAIAIBwAAKMCACASAQAA1QEAIAcAAN8BACAMAADgAQAgDQAA0AEAIA4AANEBACB3AADcAQAweAAAAwAQeQAA3AEAMHoBAAAAAX1AAM4BACGTAUAAzgEAIZYBAQDUAQAhlwECANMBACGYAQgA3QEAIZkBIADeAQAhmgECANMBACGbAQgA3QEAIZwBAQAAAAECAAAAEgAgFAAAowIAIAIAAAChAgAgFAAAogIAIA13AACgAgAweAAAoQIAEHkAAKACADB6AQDLAQAhfUAAzgEAIZMBQADOAQAhlgEBANQBACGXAQIA0wEAIZgBCADdAQAhmQEgAN4BACGaAQIA0wEAIZsBCADdAQAhnAEBAMsBACENdwAAoAIAMHgAAKECABB5AACgAgAwegEAywEAIX1AAM4BACGTAUAAzgEAIZYBAQDUAQAhlwECANMBACGYAQgA3QEAIZkBIADeAQAhmgECANMBACGbAQgA3QEAIZwBAQDLAQAhCnoBAOsBACF9QADuAQAhkwFAAO4BACGWAQEA7QEAIZcBAgDsAQAhmAEIAIsCACGZASAAjAIAIZoBAgDsAQAhmwEIAIsCACGcAQEA6wEAIQ4BAACkAgAgBwAApQIAIA0AAKYCACAOAACnAgAgegEA6wEAIX1AAO4BACGTAUAA7gEAIZYBAQDtAQAhlwECAOwBACGYAQgAiwIAIZkBIACMAgAhmgECAOwBACGbAQgAiwIAIZwBAQDrAQAhBRsAAJIDACAcAACYAwAgqAEAAJMDACCpAQAAlwMAIKwBAAABACALGwAAwAIAMBwAAMUCADCoAQAAwQIAMKkBAADCAgAwqgEAAMQCADCrAQAAxAIAMKwBAADEAgAwrQEAAMQCADCuAQAAxgIAMK8BAADHAgAwsAEAAMMCACALGwAAtAIAMBwAALkCADCoAQAAtQIAMKkBAAC2AgAwqgEAALgCADCrAQAAuAIAMKwBAAC4AgAwrQEAALgCADCuAQAAugIAMK8BAAC7AgAwsAEAALcCACALGwAAqAIAMBwAAK0CADCoAQAAqQIAMKkBAACqAgAwqgEAAKwCADCrAQAArAIAMKwBAACsAgAwrQEAAKwCADCuAQAArgIAMK8BAACvAgAwsAEAAKsCACAIBgAA8gEAIAgAAPQBACB6AQAAAAF7AgAAAAF8AQAAAAF9QAAAAAF-AQAAAAGAAQEAAAABAgAAABkAIBsAALMCACADAAAAGQAgGwAAswIAIBwAALICACABFAAAlgMAMA0FAADWAQAgBgAA1QEAIAgAANcBACB3AADSAQAweAAACwAQeQAA0gEAMHoBAAAAAXsCANMBACF8AQDUAQAhfUAAzgEAIX4BAMsBACF_AQDLAQAhgAEBAAAAAQIAAAAZACAUAACyAgAgAgAAALACACAUAACxAgAgCncAAK8CADB4AACwAgAQeQAArwIAMHoBAMsBACF7AgDTAQAhfAEA1AEAIX1AAM4BACF-AQDLAQAhfwEAywEAIYABAQDLAQAhCncAAK8CADB4AACwAgAQeQAArwIAMHoBAMsBACF7AgDTAQAhfAEA1AEAIX1AAM4BACF-AQDLAQAhfwEAywEAIYABAQDLAQAhBnoBAOsBACF7AgDsAQAhfAEA7QEAIX1AAO4BACF-AQDrAQAhgAEBAOsBACEIBgAA7wEAIAgAAPEBACB6AQDrAQAhewIA7AEAIXwBAO0BACF9QADuAQAhfgEA6wEAIYABAQDrAQAhCAYAAPIBACAIAAD0AQAgegEAAAABewIAAAABfAEAAAABfUAAAAABfgEAAAABgAEBAAAAAQkGAACDAgAgBwAAhAIAIAkAAIUCACB6AQAAAAF9QAAAAAF-AQAAAAGMAQEAAAABjgEAAACOAQKPAQEAAAABAgAAABYAIBsAAL8CACADAAAAFgAgGwAAvwIAIBwAAL4CACABFAAAlQMAMA4FAADWAQAgBgAA1QEAIAcAANoBACAJAADbAQAgdwAA2AEAMHgAAAkAEHkAANgBADB6AQAAAAF9QADOAQAhfgEAywEAIX8BAMsBACGMAQEA1AEAIY4BAADZAY4BIo8BAQAAAAECAAAAFgAgFAAAvgIAIAIAAAC8AgAgFAAAvQIAIAp3AAC7AgAweAAAvAIAEHkAALsCADB6AQDLAQAhfUAAzgEAIX4BAMsBACF_AQDLAQAhjAEBANQBACGOAQAA2QGOASKPAQEAywEAIQp3AAC7AgAweAAAvAIAEHkAALsCADB6AQDLAQAhfUAAzgEAIX4BAMsBACF_AQDLAQAhjAEBANQBACGOAQAA2QGOASKPAQEAywEAIQZ6AQDrAQAhfUAA7gEAIX4BAOsBACGMAQEA7QEAIY4BAAD4AY4BIo8BAQDrAQAhCQYAAPoBACAHAAD7AQAgCQAA_AEAIHoBAOsBACF9QADuAQAhfgEA6wEAIYwBAQDtAQAhjgEAAPgBjgEijwEBAOsBACEJBgAAgwIAIAcAAIQCACAJAACFAgAgegEAAAABfUAAAAABfgEAAAABjAEBAAAAAY4BAAAAjgECjwEBAAAAAQgIAACVAgAgegEAAAABfUAAAAABkAFAAAAAAZEBQAAAAAGSAQgAAAABkwFAAAAAAZQBIAAAAAECAAAABwAgGwAAywIAIAMAAAAHACAbAADLAgAgHAAAygIAIAEUAACUAwAwDQQAANYBACAIAADkAQAgdwAA4wEAMHgAAAUAEHkAAOMBADB6AQAAAAF9QADOAQAhfwEAywEAIZABQADOAQAhkQFAAM4BACGSAQgA3QEAIZMBQADOAQAhlAEgAN4BACECAAAABwAgFAAAygIAIAIAAADIAgAgFAAAyQIAIAt3AADHAgAweAAAyAIAEHkAAMcCADB6AQDLAQAhfUAAzgEAIX8BAMsBACGQAUAAzgEAIZEBQADOAQAhkgEIAN0BACGTAUAAzgEAIZQBIADeAQAhC3cAAMcCADB4AADIAgAQeQAAxwIAMHoBAMsBACF9QADOAQAhfwEAywEAIZABQADOAQAhkQFAAM4BACGSAQgA3QEAIZMBQADOAQAhlAEgAN4BACEHegEA6wEAIX1AAO4BACGQAUAA7gEAIZEBQADuAQAhkgEIAIsCACGTAUAA7gEAIZQBIACMAgAhCAgAAI4CACB6AQDrAQAhfUAA7gEAIZABQADuAQAhkQFAAO4BACGSAQgAiwIAIZMBQADuAQAhlAEgAIwCACEICAAAlQIAIHoBAAAAAX1AAAAAAZABQAAAAAGRAUAAAAABkgEIAAAAAZMBQAAAAAGUASAAAAABDgEAAM0CACAHAADOAgAgDQAAzwIAIA4AANACACB6AQAAAAF9QAAAAAGTAUAAAAABlgEBAAAAAZcBAgAAAAGYAQgAAAABmQEgAAAAAZoBAgAAAAGbAQgAAAABnAEBAAAAAQMbAACSAwAgqAEAAJMDACCsAQAAAQAgBBsAAMACADCoAQAAwQIAMKwBAADEAgAwsAEAAMMCACAEGwAAtAIAMKgBAAC1AgAwrAEAALgCADCwAQAAtwIAIAQbAACoAgAwqAEAAKkCADCsAQAArAIAMLABAACrAgAgAxsAAJoCADCoAQAAmwIAMKwBAACdAgAwAAAAAAAKGwAA2AIAMBwAANwCADCoAQAA2QIAMKkBAADaAgAwqgEAANsCADCrAQAA2wIAMKwBAADbAgAwrQEAANsCADCuAQAA3QIAMK8BAADeAgAwA3oBAAAAAX1AAAAAAZUBAQAAAAECAAAADwAgGwAA4gIAIAMAAAAPACAbAADiAgAgHAAA4QIAIAcKAADiAQAgdwAA4QEAMHgAAA0AEHkAAOEBADB6AQAAAAF9QADOAQAhlQEBAAAAAQIAAAAPACAUAADhAgAgAgAAAN8CACAUAADgAgAgBncAAN4CADB4AADfAgAQeQAA3gIAMHoBAMsBACF9QADOAQAhlQEBAMsBACEGdwAA3gIAMHgAAN8CABB5AADeAgAwegEAywEAIX1AAM4BACGVAQEAywEAIQN6AQDrAQAhfUAA7gEAIZUBAQDrAQAhA3oBAOsBACF9QADuAQAhlQEBAOsBACEDegEAAAABfUAAAAABlQEBAAAAAQMbAADYAgAwqAEAANkCADCsAQAA2wIAMAAAAAGtAQAAAKEBAgGtAQAAAKMBAgcbAAD-AgAgHAAAgQMAIKgBAAD_AgAgqQEAAIADACCqAQAAAwAgqwEAAAMAIKwBAAASACALGwAA9QIAMBwAAPkCADCoAQAA9gIAMKkBAAD3AgAwqgEAALgCADCrAQAAuAIAMKwBAAC4AgAwrQEAALgCADCuAQAA-gIAMK8BAAC7AgAwsAEAAPgCACALGwAA7AIAMBwAAPACADCoAQAA7QIAMKkBAADuAgAwqgEAAKwCADCrAQAArAIAMKwBAACsAgAwrQEAAKwCADCuAQAA8QIAMK8BAACvAgAwsAEAAO8CACAIBQAA8wEAIAgAAPQBACB6AQAAAAF7AgAAAAF8AQAAAAF9QAAAAAF_AQAAAAGAAQEAAAABAgAAABkAIBsAAPQCACADAAAAGQAgGwAA9AIAIBwAAPMCACABFAAAkQMAMAIAAAAZACAUAADzAgAgAgAAALACACAUAADyAgAgBnoBAOsBACF7AgDsAQAhfAEA7QEAIX1AAO4BACF_AQDrAQAhgAEBAOsBACEIBQAA8AEAIAgAAPEBACB6AQDrAQAhewIA7AEAIXwBAO0BACF9QADuAQAhfwEA6wEAIYABAQDrAQAhCAUAAPMBACAIAAD0AQAgegEAAAABewIAAAABfAEAAAABfUAAAAABfwEAAAABgAEBAAAAAQkFAACCAgAgBwAAhAIAIAkAAIUCACB6AQAAAAF9QAAAAAF_AQAAAAGMAQEAAAABjgEAAACOAQKPAQEAAAABAgAAABYAIBsAAP0CACADAAAAFgAgGwAA_QIAIBwAAPwCACABFAAAkAMAMAIAAAAWACAUAAD8AgAgAgAAALwCACAUAAD7AgAgBnoBAOsBACF9QADuAQAhfwEA6wEAIYwBAQDtAQAhjgEAAPgBjgEijwEBAOsBACEJBQAA-QEAIAcAAPsBACAJAAD8AQAgegEA6wEAIX1AAO4BACF_AQDrAQAhjAEBAO0BACGOAQAA-AGOASKPAQEA6wEAIQkFAACCAgAgBwAAhAIAIAkAAIUCACB6AQAAAAF9QAAAAAF_AQAAAAGMAQEAAAABjgEAAACOAQKPAQEAAAABDQcAAM4CACAMAADjAgAgDQAAzwIAIA4AANACACB6AQAAAAF9QAAAAAGTAUAAAAABlgEBAAAAAZcBAgAAAAGYAQgAAAABmQEgAAAAAZoBAgAAAAGbAQgAAAABAgAAABIAIBsAAP4CACADAAAAAwAgGwAA_gIAIBwAAIIDACAPAAAAAwAgBwAApQIAIAwAANcCACANAACmAgAgDgAApwIAIBQAAIIDACB6AQDrAQAhfUAA7gEAIZMBQADuAQAhlgEBAO0BACGXAQIA7AEAIZgBCACLAgAhmQEgAIwCACGaAQIA7AEAIZsBCACLAgAhDQcAAKUCACAMAADXAgAgDQAApgIAIA4AAKcCACB6AQDrAQAhfUAA7gEAIZMBQADuAQAhlgEBAO0BACGXAQIA7AEAIZgBCACLAgAhmQEgAIwCACGaAQIA7AEAIZsBCACLAgAhAxsAAP4CACCoAQAA_wIAIKwBAAASACAEGwAA9QIAMKgBAAD2AgAwrAEAALgCADCwAQAA-AIAIAQbAADsAgAwqAEAAO0CADCsAQAArAIAMLABAADvAgAgBgEAAIkDACAHAACNAwAgDAAAjgMAIA0AAIcDACAOAACIAwAglgEAAOUBACAAAAMEAACGAwAgDQAAhwMAIA4AAIgDACAFBQAAhgMAIAYAAIkDACAHAACLAwAgCQAAjAMAIIwBAADlAQAgAgQAAIYDACAIAACKAwAgBAUAAIYDACAGAACJAwAgCAAAigMAIHwAAOUBACAAAAAGegEAAAABfUAAAAABfwEAAAABjAEBAAAAAY4BAAAAjgECjwEBAAAAAQZ6AQAAAAF7AgAAAAF8AQAAAAF9QAAAAAF_AQAAAAGAAQEAAAABCg0AAIQDACAOAACFAwAgegEAAAABfUAAAAABjgEAAACjAQKTAUAAAAABnQEBAAAAAZ4BAQAAAAGfAQEAAAABoQEAAAChAQICAAAAAQAgGwAAkgMAIAd6AQAAAAF9QAAAAAGQAUAAAAABkQFAAAAAAZIBCAAAAAGTAUAAAAABlAEgAAAAAQZ6AQAAAAF9QAAAAAF-AQAAAAGMAQEAAAABjgEAAACOAQKPAQEAAAABBnoBAAAAAXsCAAAAAXwBAAAAAX1AAAAAAX4BAAAAAYABAQAAAAEDAAAAJAAgGwAAkgMAIBwAAJkDACAMAAAAJAAgDQAA6gIAIA4AAOsCACAUAACZAwAgegEA6wEAIX1AAO4BACGOAQAA6AKjASKTAUAA7gEAIZ0BAQDrAQAhngEBAOsBACGfAQEA6wEAIaEBAADnAqEBIgoNAADqAgAgDgAA6wIAIHoBAOsBACF9QADuAQAhjgEAAOgCowEikwFAAO4BACGdAQEA6wEAIZ4BAQDrAQAhnwEBAOsBACGhAQAA5wKhASIOAQAAzQIAIAwAAOMCACANAADPAgAgDgAA0AIAIHoBAAAAAX1AAAAAAZMBQAAAAAGWAQEAAAABlwECAAAAAZgBCAAAAAGZASAAAAABmgECAAAAAZsBCAAAAAGcAQEAAAABAgAAABIAIBsAAJoDACADAAAAAwAgGwAAmgMAIBwAAJ4DACAQAAAAAwAgAQAApAIAIAwAANcCACANAACmAgAgDgAApwIAIBQAAJ4DACB6AQDrAQAhfUAA7gEAIZMBQADuAQAhlgEBAO0BACGXAQIA7AEAIZgBCACLAgAhmQEgAIwCACGaAQIA7AEAIZsBCACLAgAhnAEBAOsBACEOAQAApAIAIAwAANcCACANAACmAgAgDgAApwIAIHoBAOsBACF9QADuAQAhkwFAAO4BACGWAQEA7QEAIZcBAgDsAQAhmAEIAIsCACGZASAAjAIAIZoBAgDsAQAhmwEIAIsCACGcAQEA6wEAIQkEAACUAgAgegEAAAABfUAAAAABfwEAAAABkAFAAAAAAZEBQAAAAAGSAQgAAAABkwFAAAAAAZQBIAAAAAECAAAABwAgGwAAnwMAIAoEAACDAwAgDgAAhQMAIHoBAAAAAX1AAAAAAY4BAAAAowECkwFAAAAAAZ0BAQAAAAGeAQEAAAABnwEBAAAAAaEBAAAAoQECAgAAAAEAIBsAAKEDACAOAQAAzQIAIAcAAM4CACAMAADjAgAgDgAA0AIAIHoBAAAAAX1AAAAAAZMBQAAAAAGWAQEAAAABlwECAAAAAZgBCAAAAAGZASAAAAABmgECAAAAAZsBCAAAAAGcAQEAAAABAgAAABIAIBsAAKMDACADAAAABQAgGwAAnwMAIBwAAKcDACALAAAABQAgBAAAjQIAIBQAAKcDACB6AQDrAQAhfUAA7gEAIX8BAOsBACGQAUAA7gEAIZEBQADuAQAhkgEIAIsCACGTAUAA7gEAIZQBIACMAgAhCQQAAI0CACB6AQDrAQAhfUAA7gEAIX8BAOsBACGQAUAA7gEAIZEBQADuAQAhkgEIAIsCACGTAUAA7gEAIZQBIACMAgAhAwAAACQAIBsAAKEDACAcAACqAwAgDAAAACQAIAQAAOkCACAOAADrAgAgFAAAqgMAIHoBAOsBACF9QADuAQAhjgEAAOgCowEikwFAAO4BACGdAQEA6wEAIZ4BAQDrAQAhnwEBAOsBACGhAQAA5wKhASIKBAAA6QIAIA4AAOsCACB6AQDrAQAhfUAA7gEAIY4BAADoAqMBIpMBQADuAQAhnQEBAOsBACGeAQEA6wEAIZ8BAQDrAQAhoQEAAOcCoQEiAwAAAAMAIBsAAKMDACAcAACtAwAgEAAAAAMAIAEAAKQCACAHAAClAgAgDAAA1wIAIA4AAKcCACAUAACtAwAgegEA6wEAIX1AAO4BACGTAUAA7gEAIZYBAQDtAQAhlwECAOwBACGYAQgAiwIAIZkBIACMAgAhmgECAOwBACGbAQgAiwIAIZwBAQDrAQAhDgEAAKQCACAHAAClAgAgDAAA1wIAIA4AAKcCACB6AQDrAQAhfUAA7gEAIZMBQADuAQAhlgEBAO0BACGXAQIA7AEAIZgBCACLAgAhmQEgAIwCACGaAQIA7AEAIZsBCACLAgAhnAEBAOsBACEKBQAAggIAIAYAAIMCACAHAACEAgAgegEAAAABfUAAAAABfgEAAAABfwEAAAABjAEBAAAAAY4BAAAAjgECjwEBAAAAAQIAAAAWACAbAACuAwAgDgEAAM0CACAHAADOAgAgDAAA4wIAIA0AAM8CACB6AQAAAAF9QAAAAAGTAUAAAAABlgEBAAAAAZcBAgAAAAGYAQgAAAABmQEgAAAAAZoBAgAAAAGbAQgAAAABnAEBAAAAAQIAAAASACAbAACwAwAgCgQAAIMDACANAACEAwAgegEAAAABfUAAAAABjgEAAACjAQKTAUAAAAABnQEBAAAAAZ4BAQAAAAGfAQEAAAABoQEAAAChAQICAAAAAQAgGwAAsgMAIAMAAAAJACAbAACuAwAgHAAAtgMAIAwAAAAJACAFAAD5AQAgBgAA-gEAIAcAAPsBACAUAAC2AwAgegEA6wEAIX1AAO4BACF-AQDrAQAhfwEA6wEAIYwBAQDtAQAhjgEAAPgBjgEijwEBAOsBACEKBQAA-QEAIAYAAPoBACAHAAD7AQAgegEA6wEAIX1AAO4BACF-AQDrAQAhfwEA6wEAIYwBAQDtAQAhjgEAAPgBjgEijwEBAOsBACEDAAAAAwAgGwAAsAMAIBwAALkDACAQAAAAAwAgAQAApAIAIAcAAKUCACAMAADXAgAgDQAApgIAIBQAALkDACB6AQDrAQAhfUAA7gEAIZMBQADuAQAhlgEBAO0BACGXAQIA7AEAIZgBCACLAgAhmQEgAIwCACGaAQIA7AEAIZsBCACLAgAhnAEBAOsBACEOAQAApAIAIAcAAKUCACAMAADXAgAgDQAApgIAIHoBAOsBACF9QADuAQAhkwFAAO4BACGWAQEA7QEAIZcBAgDsAQAhmAEIAIsCACGZASAAjAIAIZoBAgDsAQAhmwEIAIsCACGcAQEA6wEAIQMAAAAkACAbAACyAwAgHAAAvAMAIAwAAAAkACAEAADpAgAgDQAA6gIAIBQAALwDACB6AQDrAQAhfUAA7gEAIY4BAADoAqMBIpMBQADuAQAhnQEBAOsBACGeAQEA6wEAIZ8BAQDrAQAhoQEAAOcCoQEiCgQAAOkCACANAADqAgAgegEA6wEAIX1AAO4BACGOAQAA6AKjASKTAUAA7gEAIZ0BAQDrAQAhngEBAOsBACGfAQEA6wEAIaEBAADnAqEBIgQEBAILAAkNHwQOIAUGAQABBwgDCwAIDBAGDRcEDhoFAgQAAggKBAQFAAIGAAEHAAMJDAUDBQACBgABCAAEAgoTAgsABwEKFAAEBxsADBwADR0ADh4AAg0hAA4iAAAAAAMLAA4hAA8iABAAAAADCwAOIQAPIgAQAQEAAQEBAAEFCwAVIQAYIgAZMwAWNAAXAAAAAAAFCwAVIQAYIgAZMwAWNAAXAAADCwAeIQAfIgAgAAAAAwsAHiEAHyIAIAEEAAIBBAACBQsAJSEAKCIAKTMAJjQAJwAAAAAABQsAJSEAKCIAKTMAJjQAJwMFAAIGAAEHAAMDBQACBgABBwADAwsALiEALyIAMAAAAAMLAC4hAC8iADADBQACBgABCAAEAwUAAgYAAQgABAULADUhADgiADkzADY0ADcAAAAAAAULADUhADgiADkzADY0ADcPAgEQIwERJgESJwETKAEVKgEWLAoXLQsYLwEZMQoaMgwdMwEeNAEfNQojOA0kORElOgImOwInPAIoPQIpPgIqQAIrQgosQxItRQIuRwovSBMwSQIxSgIySwo1ThQ2Txo3UAY4UQY5UgY6UwY7VAY8VgY9WAo-WRs_WwZAXQpBXhxCXwZDYAZEYQpFZB1GZSFHZgNIZwNJaANKaQNLagNMbANNbgpObyJPcQNQcwpRdCNSdQNTdgNUdwpVeiRWeypXfARYfQRZfgRafwRbgAEEXIIBBF2EAQpehQErX4cBBGCJAQphigEsYosBBGOMAQRkjQEKZZABLWaRATFnkgEFaJMBBWmUAQVqlQEFa5YBBWyYAQVtmgEKbpsBMm-dAQVwnwEKcaABM3KhAQVzogEFdKMBCnWmATR2pwE6"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer: Buffer2 } = await import("buffer");
  const wasmArray = Buffer2.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.js"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.js");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// generated/prisma/internal/prismaNamespace.ts
var prismaNamespace_exports = {};
__export(prismaNamespace_exports, {
  AnyNull: () => AnyNull2,
  AvailabilityScalarFieldEnum: () => AvailabilityScalarFieldEnum,
  BookingScalarFieldEnum: () => BookingScalarFieldEnum,
  CategoryScalarFieldEnum: () => CategoryScalarFieldEnum,
  DbNull: () => DbNull2,
  Decimal: () => Decimal2,
  JsonNull: () => JsonNull2,
  ModelName: () => ModelName,
  NullTypes: () => NullTypes2,
  NullsOrder: () => NullsOrder,
  PrismaClientInitializationError: () => PrismaClientInitializationError2,
  PrismaClientKnownRequestError: () => PrismaClientKnownRequestError2,
  PrismaClientRustPanicError: () => PrismaClientRustPanicError2,
  PrismaClientUnknownRequestError: () => PrismaClientUnknownRequestError2,
  PrismaClientValidationError: () => PrismaClientValidationError2,
  QueryMode: () => QueryMode,
  ReviewScalarFieldEnum: () => ReviewScalarFieldEnum,
  SortOrder: () => SortOrder,
  Sql: () => Sql2,
  TransactionIsolationLevel: () => TransactionIsolationLevel,
  TutorProfileScalarFieldEnum: () => TutorProfileScalarFieldEnum,
  UserScalarFieldEnum: () => UserScalarFieldEnum,
  defineExtension: () => defineExtension,
  empty: () => empty2,
  getExtensionContext: () => getExtensionContext,
  join: () => join2,
  prismaVersion: () => prismaVersion,
  raw: () => raw2,
  sql: () => sql
});
import * as runtime2 from "@prisma/client/runtime/client";
var PrismaClientKnownRequestError2 = runtime2.PrismaClientKnownRequestError;
var PrismaClientUnknownRequestError2 = runtime2.PrismaClientUnknownRequestError;
var PrismaClientRustPanicError2 = runtime2.PrismaClientRustPanicError;
var PrismaClientInitializationError2 = runtime2.PrismaClientInitializationError;
var PrismaClientValidationError2 = runtime2.PrismaClientValidationError;
var sql = runtime2.sqltag;
var empty2 = runtime2.empty;
var join2 = runtime2.join;
var raw2 = runtime2.raw;
var Sql2 = runtime2.Sql;
var Decimal2 = runtime2.Decimal;
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var prismaVersion = {
  client: "7.4.1",
  engine: "55ae170b1ced7fc6ed07a15f110549408c501bb3"
};
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var DbNull2 = runtime2.DbNull;
var JsonNull2 = runtime2.JsonNull;
var AnyNull2 = runtime2.AnyNull;
var ModelName = {
  User: "User",
  TutorProfile: "TutorProfile",
  Category: "Category",
  Availability: "Availability",
  Booking: "Booking",
  Review: "Review"
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var UserScalarFieldEnum = {
  id: "id",
  email: "email",
  password: "password",
  name: "name",
  role: "role",
  status: "status",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var TutorProfileScalarFieldEnum = {
  id: "id",
  bio: "bio",
  experience: "experience",
  hourlyRate: "hourlyRate",
  isFeatured: "isFeatured",
  totalReviews: "totalReviews",
  averageRating: "averageRating",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  userId: "userId"
};
var CategoryScalarFieldEnum = {
  id: "id",
  categoryName: "categoryName",
  createdAt: "createdAt"
};
var AvailabilityScalarFieldEnum = {
  id: "id",
  startTime: "startTime",
  endTime: "endTime",
  totalPrice: "totalPrice",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  isBooked: "isBooked",
  tutorId: "tutorId"
};
var BookingScalarFieldEnum = {
  id: "id",
  notes: "notes",
  status: "status",
  tutorId: "tutorId",
  studentId: "studentId",
  availabilityId: "availabilityId",
  createdAt: "createdAt"
};
var ReviewScalarFieldEnum = {
  id: "id",
  rating: "rating",
  comment: "comment",
  createdAt: "createdAt",
  studentId: "studentId",
  tutorId: "tutorId",
  bookingId: "bookingId"
};
var SortOrder = {
  asc: "asc",
  desc: "desc"
};
var QueryMode = {
  default: "default",
  insensitive: "insensitive"
};
var NullsOrder = {
  first: "first",
  last: "last"
};
var defineExtension = runtime2.Extensions.defineExtension;

// generated/prisma/enums.ts
var UserRole = {
  ADMIN: "ADMIN",
  TUTOR: "TUTOR",
  STUDENT: "STUDENT"
};

// generated/prisma/client.ts
var PrismaClient = getPrismaClientClass();

// src/config/index.ts
import dotenv from "dotenv";
import path from "path";
dotenv.config({ path: path.join(process.cwd(), ".env") });
var config_default = {
  port: process.env.PORT,
  database_url: process.env.DATABASE_URL,
  jwt_secret: process.env.JWT_SECRET,
  admin_email: process.env.ADMIN_EMAIL,
  admin_password: process.env.ADMIN_PASSWORD,
  node_env: process.env.NODE_ENV
};

// src/lib/prisma.ts
var connectionString = config_default.database_url;
var adapter = new PrismaPg({ connectionString });
var prisma = new PrismaClient({ adapter });

// src/modules/auth/auth.service.ts
import jwt from "jsonwebtoken";
var createUser = async (payload) => {
  if (payload.role === "ADMIN") {
    throw new Error("USER must be either TUTOR or STUDENT");
  }
  const hashedPassword = await bcrypt.hash(payload.password, 8);
  const result = await prisma.user.create({
    data: {
      ...payload,
      password: hashedPassword
    }
  });
  const { password, ...newResult } = result;
  return newResult;
};
var loginUser = async (payload) => {
  const user = await prisma.user.findUnique({
    where: {
      email: payload.email
    }
  });
  if (!user) {
    throw new Error("User not found");
  }
  const isPasswordValid = await bcrypt.compare(payload.password, user.password);
  if (!isPasswordValid) {
    throw new Error("Password is incorrect");
  }
  const userData = {
    id: user.id,
    name: user.name,
    email: user.email,
    role: user.role,
    status: user.status
  };
  const token = jwt.sign(userData, config_default.jwt_secret, {
    expiresIn: "1d"
  });
  return { token, data: userData };
};
var AuthService = {
  createUser,
  loginUser
};

// src/utils/sendSuccessResponse.ts
function sendSuccessResponse(res, statusCode, message, data) {
  return res.status(statusCode).json({
    success: true,
    message,
    data
  });
}

// src/modules/auth/auth.controller.ts
var createUser2 = async (req, res, next) => {
  try {
    const result = await AuthService.createUser(req.body);
    sendSuccessResponse(res, 201, "User created successfully", result);
  } catch (error) {
    next(error);
  }
};
var loginUser2 = async (req, res, next) => {
  try {
    const result = await AuthService.loginUser(req.body);
    sendSuccessResponse(res, 200, "User logged in successfully", result);
  } catch (error) {
    next(error);
  }
};
var AuthController = {
  createUser: createUser2,
  loginUser: loginUser2
};

// src/modules/auth/auth.route.ts
var router = express.Router();
router.post("/register", AuthController.createUser);
router.post("/login", AuthController.loginUser);
var AuthRoutes = router;

// src/modules/tutor/tutor.route.ts
import express2 from "express";

// src/modules/tutor/tutor.service.ts
var includeTutor = {
  categories: true,
  reviews: true,
  user: {
    select: {
      name: true,
      email: true,
      role: true,
      status: true
    }
  }
};
var getAllActiveTutors = async () => {
  const result = await prisma.tutorProfile.findMany({
    where: {
      user: {
        status: "ACTIVE"
      }
    },
    include: includeTutor
  });
  return result;
};
var getAllTutors = async () => {
  const result = await prisma.tutorProfile.findMany({
    include: includeTutor
  });
  return result;
};
var getTutorById = async (id) => {
  const result = await prisma.tutorProfile.findUnique({
    where: {
      id
    },
    include: includeTutor
  });
  if (!result) {
    throw new Error("Tutor not found");
  }
  return result;
};
var createTutorProfile = async (payload, userId) => {
  const user = await prisma.user.findUnique({
    where: {
      id: userId
    }
  });
  if (!user) {
    throw new Error("User not found");
  }
  const existingProfile = await prisma.tutorProfile.findUnique({
    where: {
      userId
    }
  });
  if (existingProfile) {
    throw new Error("Tutor profile already exists");
  }
  const { categories, ...rest } = payload;
  if (!categories || !Array.isArray(categories) || categories.length === 0) {
    throw new Error("Please select at least one category");
  }
  const validCategories = await prisma.category.findMany({
    where: {
      id: { in: categories }
    }
  });
  if (validCategories.length !== categories.length) {
    throw new Error("One or more categories are invalid");
  }
  const result = await prisma.tutorProfile.create({
    data: {
      ...rest,
      userId,
      categories: {
        connect: categories.map((id) => ({
          id
        }))
      }
    },
    include: includeTutor
  });
  return result;
};
var updateTutorProfile = async (id, payload) => {
  const tutor = await prisma.tutorProfile.findUnique({
    where: {
      userId: id
    }
  });
  if (!tutor) {
    throw new Error("Tutor not found");
  }
  const { categories, ...rest } = payload;
  let categoryUpdate = {};
  if (categories !== void 0) {
    if (!Array.isArray(categories) || categories.length === 0) {
      throw new Error("Please select at least one category");
    }
    const validCategories = await prisma.category.findMany({
      where: {
        id: { in: categories }
      }
    });
    if (validCategories.length !== categories.length) {
      throw new Error("One or more categories are invalid");
    }
    categoryUpdate = {
      set: categories.map((id2) => ({
        id: id2
      }))
    };
  }
  const result = await prisma.tutorProfile.update({
    where: {
      userId: id
    },
    data: {
      ...rest,
      categories: categoryUpdate
    },
    include: includeTutor
  });
  return result;
};
var updateTutorIsFeatured = async (tutorId) => {
  const result = await prisma.$transaction(async (tx) => {
    const tutor = await tx.tutorProfile.findUnique({
      where: {
        id: tutorId
      }
    });
    if (!tutor) {
      throw new Error("Tutor not found");
    }
    return await tx.tutorProfile.update({
      where: {
        id: tutorId
      },
      data: {
        isFeatured: !tutor.isFeatured
      },
      include: includeTutor
    });
  });
  return result;
};
var TutorService = {
  getAllActiveTutors,
  getTutorById,
  createTutorProfile,
  updateTutorProfile,
  updateTutorIsFeatured,
  getAllTutors
};

// src/modules/tutor/tutor.controller.ts
var getAllActiveTutors2 = async (req, res, next) => {
  try {
    const result = await TutorService.getAllActiveTutors();
    sendSuccessResponse(
      res,
      200,
      "All Active Tutors fetched successfully",
      result
    );
  } catch (error) {
    next(error);
  }
};
var getTutorById2 = async (req, res, next) => {
  try {
    const result = await TutorService.getTutorById(req.params.id);
    sendSuccessResponse(res, 200, "Tutor fetched successfully", result);
  } catch (error) {
    next(error);
  }
};
var createTutorProfile2 = async (req, res, next) => {
  try {
    const result = await TutorService.createTutorProfile(
      req.body,
      req.user?.id
    );
    sendSuccessResponse(res, 201, "Tutor created successfully", result);
  } catch (error) {
    next(error);
  }
};
var updateTutorProfile2 = async (req, res, next) => {
  try {
    const result = await TutorService.updateTutorProfile(
      req.user?.id,
      req.body
    );
    sendSuccessResponse(res, 200, "Tutor updated successfully", result);
  } catch (error) {
    next(error);
  }
};
var updateTutorIsFeatured2 = async (req, res, next) => {
  try {
    const result = await TutorService.updateTutorIsFeatured(
      req.params.tutorId
    );
    sendSuccessResponse(
      res,
      200,
      `Tutor is now marked ${result.isFeatured ? "featured" : "not featured"}`,
      result
    );
  } catch (error) {
    next(error);
  }
};
var getAllTutors2 = async (req, res, next) => {
  try {
    const result = await TutorService.getAllTutors();
    sendSuccessResponse(res, 200, "All tutors fetched successfully", result);
  } catch (error) {
    next(error);
  }
};
var TutorController = {
  getAllActiveTutors: getAllActiveTutors2,
  getTutorById: getTutorById2,
  createTutorProfile: createTutorProfile2,
  updateTutorProfile: updateTutorProfile2,
  updateTutorIsFeatured: updateTutorIsFeatured2,
  getAllTutors: getAllTutors2
};

// src/middlewares/auth.ts
import jwt2 from "jsonwebtoken";
function auth(...roles) {
  return async (req, res, next) => {
    try {
      const token = req.headers.authorization;
      if (!token) {
        return res.status(401).json({
          success: false,
          message: "Token not found"
        });
      }
      const decoded = jwt2.verify(
        token,
        config_default.jwt_secret
      );
      const user = await prisma.user.findUnique({
        where: {
          email: decoded.email
        }
      });
      if (!user) {
        return res.status(401).json({
          success: false,
          message: "User not found"
        });
      }
      if (user.status !== "ACTIVE") {
        return res.status(401).json({
          success: false,
          message: "User is BANNED or not active"
        });
      }
      if (roles.length > 0 && !roles.includes(decoded.role)) {
        return res.status(403).json({
          success: false,
          message: "Forbidden"
        });
      }
      req.user = user;
      next();
    } catch (error) {
      next(error);
    }
  };
}

// src/modules/tutor/tutor.route.ts
var router2 = express2.Router();
router2.post("/", auth(UserRole.TUTOR), TutorController.createTutorProfile);
router2.get("/active", TutorController.getAllActiveTutors);
router2.get("/", TutorController.getAllTutors);
router2.get("/:id", TutorController.getTutorById);
router2.put("/", auth(UserRole.TUTOR), TutorController.updateTutorProfile);
router2.put(
  "/featured/:tutorId",
  auth(UserRole.ADMIN),
  TutorController.updateTutorIsFeatured
);
var TutorRoutes = router2;

// src/modules/category/category.route.ts
import express3 from "express";

// src/modules/category/category.service.ts
var createCategory = async (payload) => {
  const category = await prisma.category.findUnique({
    where: { categoryName: payload.categoryName }
  });
  if (category) throw new Error("Category already exists");
  const result = await prisma.category.create({ data: payload });
  return result;
};
var getCategories = async () => {
  const result = await prisma.category.findMany({
    include: {
      tutors: {
        select: {
          hourlyRate: true,
          bio: true,
          experience: true,
          isFeatured: true,
          user: {
            select: {
              name: true,
              email: true,
              role: true,
              status: true
            }
          }
        }
      }
    }
  });
  return result;
};
var deleteCategory = async (id) => {
  const category = await prisma.category.findUnique({
    where: { id },
    include: { tutors: true }
  });
  if (!category) throw new Error("Category not found");
  if (category.tutors.length > 0) throw new Error("Category has tutors");
  const result = await prisma.category.delete({
    where: {
      id
    }
  });
  return result;
};
var CategoryService = {
  createCategory,
  getCategories,
  deleteCategory
};

// src/modules/category/category.controller.ts
var createCategory2 = async (req, res, next) => {
  try {
    const result = await CategoryService.createCategory(req.body);
    sendSuccessResponse(res, 201, "Category created successfully", result);
  } catch (error) {
    next(error);
  }
};
var getCategories2 = async (req, res, next) => {
  try {
    const result = await CategoryService.getCategories();
    sendSuccessResponse(res, 200, "Categories fetched successfully", result);
  } catch (error) {
    next(error);
  }
};
var deleteCategory2 = async (req, res, next) => {
  try {
    const result = await CategoryService.deleteCategory(
      req.params.id
    );
    sendSuccessResponse(res, 200, "Category deleted successfully", result);
  } catch (error) {
    next(error);
  }
};
var CategoryController = {
  createCategory: createCategory2,
  getCategories: getCategories2,
  deleteCategory: deleteCategory2
};

// src/modules/category/category.route.ts
var router3 = express3.Router();
router3.post("/", auth(UserRole.ADMIN), CategoryController.createCategory);
router3.get("/", CategoryController.getCategories);
router3.delete("/:id", auth(UserRole.ADMIN), CategoryController.deleteCategory);
var CategoryRoutes = router3;

// src/modules/availability/availability.route.ts
import express4 from "express";

// src/modules/availability/availability.service.ts
var createAvailableSlot = async (payload, userId) => {
  const user = await prisma.user.findFirst({
    where: {
      id: userId,
      role: "TUTOR",
      status: "ACTIVE"
    }
  });
  if (!user) {
    throw new Error("User is not active or not found");
  }
  const tutor = await prisma.tutorProfile.findUnique({
    where: {
      userId
    }
  });
  if (!tutor) {
    throw new Error("Tutor not found");
  }
  const startDate = new Date(payload.startTime);
  const endDate = new Date(payload.endTime);
  if (startDate <= /* @__PURE__ */ new Date()) {
    throw new Error("Start time must be in the future");
  }
  if (endDate <= startDate) {
    throw new Error("End time must be after start time");
  }
  const durationInHour = (endDate.getTime() - startDate.getTime()) / (1e3 * 60 * 60);
  if (durationInHour < 1 || durationInHour > 3) {
    throw new Error("Duration must be between 1 and 3 hours");
  }
  const overlapping = await prisma.availability.findFirst({
    where: {
      tutorId: tutor.id,
      AND: [{ startTime: { lt: endDate } }, { endTime: { gt: startDate } }]
    }
  });
  if (overlapping) {
    throw new Error("Availability overlaps with existing slot");
  }
  const totalPrice = durationInHour * tutor.hourlyRate;
  const result = await prisma.availability.create({
    data: {
      tutorId: tutor.id,
      ...payload,
      totalPrice
    },
    include: {
      tutorProfile: {
        select: {
          bio: true,
          experience: true,
          hourlyRate: true,
          isFeatured: true,
          user: {
            select: {
              name: true,
              email: true,
              role: true,
              status: true
            }
          }
        }
      }
    }
  });
  return result;
};
var getAvailableTimeSlots = async (userId) => {
  const tutor = await prisma.tutorProfile.findUnique({
    where: {
      userId
    },
    include: {
      user: {
        select: {
          name: true,
          email: true,
          role: true,
          status: true
        }
      }
    }
  });
  if (!tutor) {
    throw new Error("Tutor not found");
  }
  const result = await prisma.availability.findMany({
    where: {
      tutorId: tutor.id
    },
    include: {
      tutorProfile: {
        select: {
          bio: true,
          experience: true,
          hourlyRate: true,
          isFeatured: true,
          user: {
            select: {
              name: true,
              email: true,
              role: true,
              status: true
            }
          }
        }
      }
    }
  });
  return result;
};
var getAllAvailableTimeSlots = async () => {
  const result = await prisma.availability.findMany({
    include: {
      tutorProfile: {
        select: {
          bio: true,
          experience: true,
          hourlyRate: true,
          isFeatured: true,
          user: {
            select: {
              name: true,
              email: true,
              role: true,
              status: true
            }
          }
        }
      }
    }
  });
  return result;
};
var getAvailableTimeSlotById = async (id) => {
  const result = await prisma.availability.findUnique({
    where: {
      id
    },
    include: {
      tutorProfile: {
        select: {
          bio: true,
          experience: true,
          hourlyRate: true,
          isFeatured: true,
          user: {
            select: {
              name: true,
              email: true,
              role: true,
              status: true
            }
          }
        }
      }
    }
  });
  if (!result) {
    throw new Error("Availability not found");
  }
  return result;
};
var AvailabilityService = {
  createAvailableSlot,
  getAvailableTimeSlots,
  getAllAvailableTimeSlots,
  getAvailableTimeSlotById
};

// src/modules/availability/availability.controller.ts
var createAvailableSlot2 = async (req, res, next) => {
  try {
    const result = await AvailabilityService.createAvailableSlot(
      req.body,
      req.user?.id
    );
    sendSuccessResponse(
      res,
      201,
      "Available slot created successfully",
      result
    );
  } catch (error) {
    next(error);
  }
};
var getAvailableTimeSlots2 = async (req, res, next) => {
  try {
    const result = await AvailabilityService.getAvailableTimeSlots(
      req.user?.id
    );
    sendSuccessResponse(
      res,
      200,
      "Available time slots fetched successfully",
      result
    );
  } catch (error) {
    next(error);
  }
};
var getAllAvailableTimeSlots2 = async (req, res, next) => {
  try {
    const result = await AvailabilityService.getAllAvailableTimeSlots();
    sendSuccessResponse(
      res,
      200,
      "Available time slots fetched successfully",
      result
    );
  } catch (error) {
    next(error);
  }
};
var getAvailableTimeSlotById2 = async (req, res, next) => {
  try {
    const result = await AvailabilityService.getAvailableTimeSlotById(
      req.params.id
    );
    sendSuccessResponse(
      res,
      200,
      "Available time slot fetched successfully",
      result
    );
  } catch (error) {
    next(error);
  }
};
var AvailabilityController = {
  createAvailableSlot: createAvailableSlot2,
  getAvailableTimeSlots: getAvailableTimeSlots2,
  getAllAvailableTimeSlots: getAllAvailableTimeSlots2,
  getAvailableTimeSlotById: getAvailableTimeSlotById2
};

// src/modules/availability/availability.route.ts
var router4 = express4.Router();
router4.post(
  "/",
  auth(UserRole.TUTOR),
  AvailabilityController.createAvailableSlot
);
router4.get(
  "/",
  auth(UserRole.TUTOR),
  AvailabilityController.getAvailableTimeSlots
);
router4.get(
  "/all",
  auth(UserRole.ADMIN),
  AvailabilityController.getAllAvailableTimeSlots
);
router4.get("/:id", AvailabilityController.getAvailableTimeSlotById);
var AvailabilityRoutes = router4;

// src/modules/booking/booking.route.ts
import express5 from "express";

// src/modules/booking/booking.service.ts
var bookingInclude = {
  availability: {
    select: {
      startTime: true,
      endTime: true,
      isBooked: true,
      totalPrice: true
    }
  },
  student: {
    select: {
      name: true,
      email: true,
      role: true,
      status: true
    }
  },
  tutor: {
    select: {
      bio: true,
      experience: true,
      hourlyRate: true,
      isFeatured: true,
      user: {
        select: {
          name: true,
          email: true,
          role: true,
          status: true
        }
      }
    }
  }
};
var createBooking = async (studentId, availabilityId, payload) => {
  const result = await prisma.$transaction(async (tx) => {
    const student = await tx.user.findFirst({
      where: {
        id: studentId,
        role: "STUDENT",
        status: "ACTIVE"
      }
    });
    if (!student) throw new Error("Student is not active or not found");
    const availability = await tx.availability.findUnique({
      where: {
        id: availabilityId
      }
    });
    if (!availability) throw new Error("Availability not found");
    if (availability.isBooked) {
      throw new Error("This slot is already booked");
    }
    if (availability.tutorId === studentId) {
      throw new Error("You cannot book your own slot");
    }
    const bookingData = {
      tutorId: availability.tutorId,
      studentId,
      availabilityId,
      ...payload
    };
    await tx.availability.update({
      where: {
        id: availabilityId
      },
      data: {
        isBooked: true
      }
    });
    const booking = await tx.booking.create({
      data: bookingData,
      include: bookingInclude
    });
    return booking;
  });
  return result;
};
var getAllBookings = async (userId) => {
  const user = await prisma.user.findUnique({
    where: {
      id: userId
    },
    select: {
      role: true
    }
  });
  if (!user) throw new Error("User not found");
  let result;
  switch (user.role) {
    case "ADMIN":
      result = await prisma.booking.findMany({
        include: bookingInclude
      });
      break;
    case "STUDENT":
      result = await prisma.booking.findMany({
        where: {
          studentId: userId
        },
        include: bookingInclude
      });
      break;
    case "TUTOR":
      result = await prisma.booking.findMany({
        where: {
          tutor: {
            userId
          }
        },
        include: bookingInclude
      });
      break;
    default:
      break;
  }
  return result;
};
var getBookingById = async (id, userId) => {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { role: true }
  });
  if (!user) throw new Error("User not found");
  let booking;
  if (user.role === "ADMIN") {
    booking = await prisma.booking.findUnique({
      where: { id },
      include: bookingInclude
    });
  }
  if (user.role === "STUDENT") {
    booking = await prisma.booking.findFirst({
      where: {
        id,
        studentId: userId
      },
      include: bookingInclude
    });
  }
  if (user.role === "TUTOR") {
    booking = await prisma.booking.findFirst({
      where: {
        id,
        tutor: {
          userId
        }
      },
      include: bookingInclude
    });
  }
  if (!booking) {
    throw new Error("Booking not found or access denied");
  }
  return booking;
};
var createReview = async (payload, bookingId, studentId) => {
  const result = await prisma.$transaction(async (tx) => {
    const booking = await tx.booking.findFirst({
      where: {
        id: bookingId,
        status: "COMPLETED",
        studentId,
        student: {
          status: "ACTIVE"
        }
      },
      include: {
        review: true,
        tutor: true
      }
    });
    if (!booking)
      throw new Error("Booking not found or status is not completed");
    if (booking.review) throw new Error("Review already created");
    if (payload.rating < 1 || payload.rating > 5)
      throw new Error("Rating must be between 1 and 5");
    const review = await tx.review.create({
      data: {
        rating: payload.rating,
        comment: payload.comment,
        bookingId,
        studentId,
        tutorId: booking.tutorId
      },
      include: {
        student: {
          select: {
            name: true,
            email: true,
            role: true,
            status: true
          }
        },
        tutor: {
          select: {
            user: {
              select: {
                name: true,
                email: true,
                role: true,
                status: true
              }
            }
          }
        }
      }
    });
    const tutor = booking.tutor;
    const newTotalReviews = tutor.totalReviews + 1;
    const newAverageRating = parseFloat(
      ((tutor.averageRating * tutor.totalReviews + payload.rating) / newTotalReviews).toFixed(2)
    );
    await tx.tutorProfile.update({
      where: { id: tutor.id },
      data: {
        totalReviews: newTotalReviews,
        averageRating: newAverageRating
      }
    });
    return review;
  });
  return result;
};
var BookingService = {
  createBooking,
  getAllBookings,
  getBookingById,
  createReview
};

// src/modules/booking/booking.controller.ts
var createBooking2 = async (req, res, next) => {
  try {
    const studentId = req.user?.id;
    const availabilityId = req.params.availabilityId;
    const result = await BookingService.createBooking(
      studentId,
      availabilityId,
      req.body
    );
    sendSuccessResponse(res, 201, "Booking created successfully", result);
  } catch (error) {
    next(error);
  }
};
var getAllBookings2 = async (req, res, next) => {
  try {
    const result = await BookingService.getAllBookings(req.user?.id);
    sendSuccessResponse(res, 200, "Bookings fetched successfully", result);
  } catch (error) {
    next(error);
  }
};
var getBookingById2 = async (req, res, next) => {
  try {
    const result = await BookingService.getBookingById(
      req.params.bookingId,
      req.user?.id
    );
    sendSuccessResponse(res, 200, "Booking fetched successfully", result);
  } catch (error) {
    next(error);
  }
};
var createReview2 = async (req, res, next) => {
  try {
    const result = await BookingService.createReview(
      req.body,
      req.params.bookingId,
      req.user?.id
    );
    sendSuccessResponse(res, 201, "Review created successfully", result);
  } catch (error) {
    next(error);
  }
};
var BookingController = {
  createBooking: createBooking2,
  getAllBookings: getAllBookings2,
  getBookingById: getBookingById2,
  createReview: createReview2
};

// src/modules/booking/booking.route.ts
var router5 = express5.Router();
router5.post(
  "/availability/:availabilityId",
  auth(UserRole.STUDENT),
  BookingController.createBooking
);
router5.post(
  "/:bookingId/review",
  auth(UserRole.STUDENT),
  BookingController.createReview
);
router5.get(
  "/",
  auth(UserRole.ADMIN, UserRole.TUTOR, UserRole.STUDENT),
  BookingController.getAllBookings
);
router5.get(
  "/:bookingId",
  auth(UserRole.ADMIN, UserRole.TUTOR, UserRole.STUDENT),
  BookingController.getBookingById
);
var BookingRoutes = router5;

// src/modules/review/review.route.ts
import { Router } from "express";

// src/modules/review/review.service.ts
var reviewInclude = {
  student: {
    select: {
      name: true,
      email: true,
      role: true,
      status: true
    }
  },
  tutor: {
    select: {
      user: {
        select: {
          name: true,
          email: true
        }
      }
    }
  }
};
var getAllReviews = async () => {
  const reviews = await prisma.review.findMany({
    include: reviewInclude
  });
  return reviews;
};
var getReviewById = async (id) => {
  const review = await prisma.review.findUnique({
    where: {
      id
    },
    include: reviewInclude
  });
  return review;
};
var ReviewService = {
  getAllReviews,
  getReviewById
};

// src/modules/review/review.controller.ts
var getAllReviews2 = async (req, res, next) => {
  try {
    const result = await ReviewService.getAllReviews();
    sendSuccessResponse(res, 200, "Reviews fetched successfully", result);
  } catch (error) {
    next(error);
  }
};
var getReviewById2 = async (req, res, next) => {
  try {
    const result = await ReviewService.getReviewById(req.params.id);
    sendSuccessResponse(res, 200, "Review fetched successfully", result);
  } catch (error) {
    next(error);
  }
};
var ReviewController = {
  getAllReviews: getAllReviews2,
  getReviewById: getReviewById2
};

// src/modules/review/review.route.ts
var router6 = Router();
router6.get("/", ReviewController.getAllReviews);
router6.get("/:id", ReviewController.getReviewById);
var ReviewRoutes = router6;

// src/modules/user/user.route.ts
import express6 from "express";

// src/modules/user/user.service.ts
var getAllUsers = async () => {
  return await prisma.user.findMany({
    include: {
      tutorProfile: true
    },
    omit: {
      password: true
    }
  });
};
var getUserById = async (userId) => {
  return await prisma.user.findUnique({
    where: {
      id: userId
    },
    include: {
      tutorProfile: true
    },
    omit: {
      password: true
    }
  });
};
var updateUserStatus = async (userId) => {
  const result = await prisma.$transaction(async (tx) => {
    const user = await tx.user.findUnique({
      where: {
        id: userId
      },
      include: {
        tutorProfile: true
      },
      omit: {
        password: true
      }
    });
    if (!user) {
      throw new Error("User not found");
    }
    const updatedUser = await tx.user.update({
      where: {
        id: userId
      },
      data: {
        status: user.status === "ACTIVE" ? "BANNED" : "ACTIVE"
      },
      include: {
        tutorProfile: true
      },
      omit: {
        password: true
      }
    });
    return updatedUser;
  });
  return result;
};
var UserService = {
  getAllUsers,
  updateUserStatus,
  getUserById
};

// src/modules/user/user.controller.ts
var getAllUsers2 = async (req, res, next) => {
  try {
    const result = await UserService.getAllUsers();
    sendSuccessResponse(res, 200, "All users fetched successfully", result);
  } catch (error) {
    next(error);
  }
};
var getUserById2 = async (req, res, next) => {
  try {
    const result = await UserService.getUserById(req.params.id);
    sendSuccessResponse(res, 200, "User fetched successfully", result);
  } catch (error) {
    next(error);
  }
};
var updateUserStatus2 = async (req, res, next) => {
  try {
    const result = await UserService.updateUserStatus(req.params.id);
    sendSuccessResponse(res, 200, `User is now ${result.status}`, result);
  } catch (error) {
    next(error);
  }
};
var UserController = {
  getAllUsers: getAllUsers2,
  getUserById: getUserById2,
  updateUserStatus: updateUserStatus2
};

// src/modules/user/user.route.ts
var router7 = express6.Router();
router7.get("/", auth(UserRole.ADMIN), UserController.getAllUsers);
router7.get("/:id", auth(UserRole.ADMIN), UserController.getUserById);
router7.put(
  "/status/:id",
  auth(UserRole.ADMIN),
  UserController.updateUserStatus
);
var UserRoutes = router7;

// src/routes/index.ts
var router8 = Router2();
var routerManager = [
  {
    path: "/auth",
    route: AuthRoutes
  },
  {
    path: "/tutors",
    route: TutorRoutes
  },
  {
    path: "/categories",
    route: CategoryRoutes
  },
  {
    path: "/availability",
    route: AvailabilityRoutes
  },
  {
    path: "/bookings",
    route: BookingRoutes
  },
  {
    path: "/reviews",
    route: ReviewRoutes
  },
  {
    path: "/users",
    route: UserRoutes
  }
];
routerManager.forEach((route) => {
  router8.use(route.path, route.route);
});
var routes_default = router8;

// src/middlewares/globalErrorHandler.ts
var globalErrorHandler = (error, req, res, next) => {
  let statusCode = 500;
  let message = "Something went wrong";
  if (error instanceof prismaNamespace_exports.PrismaClientKnownRequestError) {
    statusCode = 400;
    switch (error.code) {
      // Unique constraint failed
      case "P2002":
        message = `Duplicate value for field: ${error.meta?.target}`;
        break;
      // Record not found
      case "P2025":
        message = "Record not found";
        break;
      // Foreign key constraint failed
      case "P2003":
        message = "Invalid reference ID";
        break;
      default:
        message = "Database error occurred";
    }
  } else if (error instanceof prismaNamespace_exports.PrismaClientValidationError) {
    statusCode = 400;
    message = "Invalid data provided";
  } else if (error instanceof prismaNamespace_exports.PrismaClientUnknownRequestError) {
    statusCode = 500;
    message = "Error occurred during query execution";
  } else if (error instanceof prismaNamespace_exports.PrismaClientInitializationError) {
    if (error.errorCode === "P1001") {
      statusCode = 401;
      message = "Authentication failed, please check your credentials";
    } else if (error.errorCode === "P1000") {
      statusCode = 400;
      message = "Can't connect to database";
    }
  } else if (error instanceof Error) {
    statusCode = 400;
    message = error.message;
  }
  res.status(statusCode).json({
    success: false,
    message,
    data: null,
    error: config_default.node_env === "development" ? error : void 0
  });
};
var globalErrorHandler_default = globalErrorHandler;

// src/middlewares/notFound.ts
function notFound(req, res) {
  res.status(404).json({
    success: false,
    message: "Route not found",
    path: req.originalUrl,
    date: /* @__PURE__ */ new Date()
  });
}

// src/app.ts
var app = express7();
app.use(express7.json());
app.use(cors());
app.use("/api", routes_default);
app.get("/", (req, res) => {
  res.send("Hello from Skill-Bridge backend!");
});
app.use(globalErrorHandler_default);
app.use(notFound);
var app_default = app;

// src/lib/cron.ts
import cron from "node-cron";
var initCronJobs = () => {
  cron.schedule("*/5 * * * *", async () => {
    console.log("Checking for completed bookings...");
    try {
      await prisma.booking.updateMany({
        where: {
          status: "CONFIRMED",
          availability: {
            endTime: { lt: /* @__PURE__ */ new Date() }
          }
        },
        data: { status: "COMPLETED" }
      });
    } catch (error) {
      console.error("Cron Job Error:", error);
    }
  });
};

// src/server.ts
var port = config_default.port || 4e3;
async function main() {
  try {
    await prisma.$connect();
    console.log("Connected to database successfully");
    app_default.listen(port, () => {
      console.log(`App listening on port ${port}`);
    });
    initCronJobs();
  } catch (error) {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  }
}
main();
